name: widgify
description: "EMI Widgify App"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.0.0
  shared_preferences: ^2.3.4
  google_fonts: ^6.2.1
  provider: ^6.0.0
  intl: ^0.20.1
  audioplayers: ^6.1.0
  file_picker: ^8.1.7
  metadata_god: ^1.0.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true



